PasswordAuthentication no
KbdInteractiveAuthentication no
PrintMotd no
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
PermitTunnel no
AuthenticationMethods publickey
PubkeyAcceptedAlgorithms ssh-ed25519
HostKeyAlgorithms ssh-ed25519
PermitRootLogin prohibit-password
LoginGraceTime 20
MaxAuthTries 3
MaxSessions 5
AllowUsers git