services:
  mugit:
    build:
      context: .
      dockerfile: ./dockerfile
      network: host
      args:
        MUGIT_UID: ${MUGIT_UID}
        MUGIT_GID: ${MUGIT_GID}
    image: alpine:3.24-custom
    container_name: mugit
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
    ports:
      - ${MUGIT_PORT}:22
    volumes:
      - ${MUGIT_DIR}:/home/git:rw
      - ./entrypoint.sh:/entrypoint.sh:rw
      - ./sshd_config.conf:/etc/ssh/sshd_config.d/sshd_config.conf:ro
      - ./gitconfig:/etc/gitconfig:ro
      - ./git-shell-commands:/home/git/git-shell-commands:ro
      - ./api.sh:/usr/local/bin/api:ro
    # networks:
    #   web-network:
    #     ipv4_address: 172.18.0.60
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 22"]
      interval: 30s
      timeout: 5s
      retries: 3

# networks:
#   web-network:
#     external: true