FROM alpine:3.24

ARG CORE_UID=1000
ARG CORE_GID=1000
ARG CORE_SOCKET_PORT=8082

RUN apk update && \
    apk add --no-cache tzdata openssh-server git socat && \
    rm -rf /var/cache/apk/*

RUN addgroup --gid ${CORE_GID} git && \
    adduser --uid ${CORE_UID} --ingroup git --home /home/git --shell /usr/bin/git-shell --disabled-password git && \
    passwd -u git
    
EXPOSE ${CORE_SOCKET_PORT}/tcp

WORKDIR /home/git
    
ENTRYPOINT ["/entrypoint.sh"]