# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.name: '%env(string:APP_NAME)%'
    app.env: '%env(string:APP_ENV)%'
    turbo.enable_prefetch: '%env(bool:TURBO_PREFETCH_ENABLE)%'
    hub.base_url: '%env(string:HUB_BASE_URL)%'
    iam.base_url: '%env(string:IAM_BASE_URL)%'
    core.host_addr: '%env(string:CORE_HOST_ADDR)%'
    core.host_port: '%env(int:CORE_HOST_PORT)%'
    core.host_pubkey: '%env(string:CORE_HOST_PUBKEY)%'
    core.root_prikey: '%env(string:CORE_ROOT_PRIKEY)%'
    core.timeout: '%env(int:CORE_TIMEOUT)%'
    core.repo_max_size_mio: '%env(int:CORE_REPO_MAX_SIZE_MIO)%'
    core.repo_warn_size_percent: '%env(int:CORE_REPO_WARN_SIZE_PERCENT)%'
    mock.keycloak_enable: '%env(bool:MOCK_KEYCLOAK_ENABLE)%'

imports:
    - { resource: 'version.yaml' }

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'

    Symfony\Component\Dotenv\Command\DotenvDumpCommand: ~
    
when@dev: &services_dev
    services:
        App\Tests\Mock\KeycloakMockEntryPoint:
            decorates: 'Mainick\KeycloakClientBundle\Security\EntryPoint\KeycloakAuthenticationEntryPoint'
            autowire: true
            autoconfigure: true

        App\Tests\Mock\KeycloakMockUserProvider:
            autowire: true
            autoconfigure: true

        App\Tests\Mock\KeycloakMockUserCreate:
            autowire: true
            autoconfigure: true
    
    parameters:
        core.data: '%env(string:CORE_DATA)%'

when@test: *services_dev