twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    globals: 
        env:
            app:
                name: '%app.name%'
                env: '%app.env%'
                enable_prefetch: '%app.enable_prefetch%'
                hub_url: '%app.hub_url%'
            versioning:
                version: '%versioning.version%'
                version_hash: '%versioning.version_hash%'
                release_date: '%versioning.release_date%'

when@test:
    twig:
        strict_variables: true
