twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    globals: 
        env:
            app:
                name: '%app.name%'
                env: '%app.env%'
            turbo:
                enable_prefetch: '%turbo.enable_prefetch%'
            hub:
                base_url: '%hub.base_url%'
            mock:
                keycloak_enable: '%mock.keycloak_enable%'
            versioning:
                version: '%versioning.version%'
                version_hash: '%versioning.version_hash%'
                release_date: '%versioning.release_date%'

when@test:
    twig:
        strict_variables: true
