name: test
run-name: 🧪 ${{ github.actor }} triggered "test", version ${{ inputs.version }}, environment ${{ inputs.environment }} 

on:
  workflow_call:
    inputs:
      environment:
        description: 'The targeted environment'
        required: true
        type: environment
      version:
        description: 'The targeted version (x.x.x)'
        required: true
        type: string
      test-unit:
        description: 'Execute unit tests'
        required: true
        default: true
        type: boolean
      test-inte:
        description: 'Execute integration tests'
        required: true
        default: true
        type: boolean
      test-func:
        description: 'Execute functionnal tests'
        required: true
        default: true
        type: boolean
      test-e2e:
        description: 'Execute end-to-end tests'
        required: true
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    outputs:
      coverage: ${{ steps.phpunit.outputs.coverage }}
    steps:
    - name: Checkout code in the runner
      uses: actions/checkout@v6

    - name: Setup php 8.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        coverage: pcov

    - name: Cache composer TEST packages
      id: composer-cache
      uses: actions/cache@v5
      with:
        path: ui/vendor
        key: ${{ runner.os }}-php-test-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-test-

    - name: Install php TEST dependencies
      run: |
        cd ui
        composer install --no-scripts --no-interaction --no-progress --prefer-dist
       
    - name: Setup Node.js 22.x
      uses: actions/setup-node@v6
      with:
        node-version: 22.x

    - name: Cache npm packages
      id: npm-cache
      uses: actions/cache@v5
      with:
        path: ui/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install node dependencies and build assets
      run: |
        cd ui
        npm install

    - name: Run all test suites and check coverage
      id: phpunit
      run: |
        cd ui
        echo "CORE_UID=$(id -u)\nCORE_GID=$(id -g)\n" > .env.test.local
        ${{ inputs.test-unit }}
        vendor/bin/phpunit --testsuite
        php vendor/bin/coverage-check var/coverage/clover.xml ${{ vars.MIN_COVERAGE }}
        coverage=$(php vendor/bin/coverage-check var/coverage/clover.xml 1 --only-percentage | grep -Eo '[0-9.]+%' | sed 's/%//')
        echo "coverage=$coverage" >> $GITHUB_OUTPUT